/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbooking;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lnasw
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        jPanelInformation = new javax.swing.JPanel();
        jPanelInfoCustomer = new javax.swing.JPanel();
        firstName = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        familyName = new javax.swing.JLabel();
        familyNameField = new javax.swing.JTextField();
        idNumber = new javax.swing.JLabel();
        idNumberField = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        jPanelInfoRoom = new javax.swing.JPanel();
        roomType = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        checkin = new javax.swing.JLabel();
        checkout = new javax.swing.JLabel();
        selectRoomType = new javax.swing.JComboBox<>();
        selectNumber = new javax.swing.JComboBox<>();
        checkinMonth = new javax.swing.JComboBox<>();
        checkoutMonth = new javax.swing.JComboBox<>();
        checkinDay = new javax.swing.JComboBox<>();
        checkoutDay = new javax.swing.JComboBox<>();
        addRoomButton = new javax.swing.JButton();
        jPanelOrder = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCustomer = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRoom = new javax.swing.JList<>();
        editCustomerButton = new javax.swing.JButton();
        deleteCustomerButton = new javax.swing.JButton();
        editRoomButton = new javax.swing.JButton();
        deleteRoomButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabelMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Booking");
        setBackground(new java.awt.Color(240, 255, 240));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        setForeground(new java.awt.Color(240, 255, 240));

        backGround.setBackground(new java.awt.Color(240, 255, 240));

        jPanelInformation.setBackground(new java.awt.Color(240, 255, 240));
        jPanelInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14))); // NOI18N

        jPanelInfoCustomer.setBackground(new java.awt.Color(240, 255, 240));
        jPanelInfoCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM));

        firstName.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        firstName.setText("First Name:");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        familyName.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        familyName.setText("Family Name:");

        idNumber.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        idNumber.setText("ID number:");

        idNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNumberFieldActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        phone.setText("Phone:");

        addCustomerButton.setBackground(new java.awt.Color(135, 206, 250));
        addCustomerButton.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        addCustomerButton.setText("ADD");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoCustomerLayout = new javax.swing.GroupLayout(jPanelInfoCustomer);
        jPanelInfoCustomer.setLayout(jPanelInfoCustomerLayout);
        jPanelInfoCustomerLayout.setHorizontalGroup(
            jPanelInfoCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInfoCustomerLayout.createSequentialGroup()
                        .addComponent(firstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(familyName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInfoCustomerLayout.createSequentialGroup()
                        .addGroup(jPanelInfoCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idNumber)
                            .addComponent(phone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInfoCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idNumberField)
                            .addComponent(phoneField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(familyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelInfoCustomerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {familyNameField, firstNameField});

        jPanelInfoCustomerLayout.setVerticalGroup(
            jPanelInfoCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoCustomerLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelInfoCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName)
                    .addComponent(familyName)
                    .addComponent(familyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idNumber)
                    .addComponent(idNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addCustomerButton))
        );

        jPanelInfoRoom.setBackground(new java.awt.Color(240, 255, 240));
        jPanelInfoRoom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM));

        roomType.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        roomType.setText("Room Type:");

        number.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        number.setText("Number of People:");

        checkin.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        checkin.setText("Check-in Date:");

        checkout.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        checkout.setText("Check-out Date:");

        selectRoomType.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        selectRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Room", "Double Room", "King Size", "Triple Room" }));
        selectRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRoomTypeActionPerformed(evt);
            }
        });

        selectNumber.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        selectNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        selectNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNumberActionPerformed(evt);
            }
        });

        checkinMonth.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        checkinMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan.", "Feb.", "Mar.", "Apr.", "May.", "Jun.", "Jul.", "Aug.", "Sept.", "Oct.", "Nov.", "Dec." }));

        checkoutMonth.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        checkoutMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan.", "Feb.", "Mar.", "Apr.", "May.", "Jun.", "Jul.", "Aug.", "Sept.", "Oct.", "Nov.", "Dec." }));

        checkinDay.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        checkinDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        checkoutDay.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        checkoutDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        addRoomButton.setBackground(new java.awt.Color(135, 206, 250));
        addRoomButton.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        addRoomButton.setText("ADD");
        addRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoRoomLayout = new javax.swing.GroupLayout(jPanelInfoRoom);
        jPanelInfoRoom.setLayout(jPanelInfoRoomLayout);
        jPanelInfoRoomLayout.setHorizontalGroup(
            jPanelInfoRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkin)
                    .addComponent(roomType)
                    .addComponent(checkout)
                    .addComponent(number))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoRoomLayout.createSequentialGroup()
                        .addComponent(checkoutMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkoutDay, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selectRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInfoRoomLayout.createSequentialGroup()
                        .addComponent(checkinMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkinDay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(selectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoRoomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelInfoRoomLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {checkinDay, checkinMonth, checkoutDay, checkoutMonth});

        jPanelInfoRoomLayout.setVerticalGroup(
            jPanelInfoRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomType))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number)
                    .addComponent(selectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkin)
                    .addComponent(checkinMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkout)
                    .addComponent(checkoutMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(addRoomButton))
        );

        javax.swing.GroupLayout jPanelInformationLayout = new javax.swing.GroupLayout(jPanelInformation);
        jPanelInformation.setLayout(jPanelInformationLayout);
        jPanelInformationLayout.setHorizontalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelInfoRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInfoCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelInformationLayout.setVerticalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addComponent(jPanelInfoCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInfoRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelOrder.setBackground(new java.awt.Color(240, 255, 240));
        jPanelOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14))); // NOI18N

        jListCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_BOTTOM));
        jScrollPane1.setViewportView(jListCustomer);

        jListRoom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_BOTTOM));
        jScrollPane2.setViewportView(jListRoom);

        editCustomerButton.setBackground(new java.awt.Color(135, 206, 250));
        editCustomerButton.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        editCustomerButton.setText("EDIT");
        editCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerButtonActionPerformed(evt);
            }
        });

        deleteCustomerButton.setBackground(new java.awt.Color(135, 206, 250));
        deleteCustomerButton.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        deleteCustomerButton.setText("DELETE");
        deleteCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerButtonActionPerformed(evt);
            }
        });

        editRoomButton.setBackground(new java.awt.Color(135, 206, 250));
        editRoomButton.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        editRoomButton.setText("EDIT");
        editRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoomButtonActionPerformed(evt);
            }
        });

        deleteRoomButton.setBackground(new java.awt.Color(135, 206, 250));
        deleteRoomButton.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        deleteRoomButton.setText("DELETE");
        deleteRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOrderLayout = new javax.swing.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelOrderLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(editCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelOrderLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(deleteCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCustomerButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelOrderLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(editRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteRoomButton)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelOrderLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteCustomerButton, editCustomerButton});

        jPanelOrderLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteRoomButton, editRoomButton});

        jLabelMap.setBackground(new java.awt.Color(240, 255, 240));
        jLabelMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map.png"))); // NOI18N
        jLabelMap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Map", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14))); // NOI18N
        jScrollPane3.setViewportView(jLabelMap);

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        backGroundLayout.setHorizontalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        backGroundLayout.setVerticalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addComponent(jPanelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
        String firstNameString = firstNameField.getText();
        String familyNameString = familyNameField.getText();
        String idNumberString = idNumberField.getText();
        String phoneString = phoneField.getText();
        Person p = new Person(firstNameString, familyNameString, idNumberString, phoneString);
        if (p.isNotEmpty()) {
            customerEmpty();
            customerListModel.addElement(p);
            jListCustomer.setModel(customerListModel);
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in the blank.", "Customer Information Missing", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    public void customerEmpty() {
        firstNameField.setText("");
        familyNameField.setText("");
        idNumberField.setText("");
        phoneField.setText("");
    }
    
    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void selectRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectRoomTypeActionPerformed

    private void selectNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectNumberActionPerformed

    private void idNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idNumberFieldActionPerformed

    private void editCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jListCustomer.getSelectedIndex();
        Person p = (Person) customerListModel.getElementAt(selectedIndex);
        if (selectedIndex == -1) {

        } else {
            customerListModel.remove(selectedIndex);
        }
        firstNameField.setText(p.getFirstName());
        familyNameField.setText(p.getFamilyName());
        idNumberField.setText(p.getIdNumber());
        phoneField.setText(p.getPhone());
    }//GEN-LAST:event_editCustomerButtonActionPerformed

    private void deleteCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jListCustomer.getSelectedIndex();
        if (selectedIndex == -1) {
            customerListModel.removeAllElements();
        } else {
            customerListModel.remove(selectedIndex);
        }
    }//GEN-LAST:event_deleteCustomerButtonActionPerformed

    private void editRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoomButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jListRoom.getSelectedIndex();
        Room r =  (Room) roomListModel.getElementAt(selectedIndex);
        System.out.println(r);
        if (selectedIndex == -1) {

        } else {
            roomListModel.remove(selectedIndex);
        }
        selectRoomType.setSelectedItem(r.getType());
        selectNumber.setSelectedItem(r.getNumber());
        checkinMonth.setSelectedItem(r.getInMonth());
        checkinDay.setSelectedItem(r.getInDay());
        checkoutMonth.setSelectedItem(r.getOutMonth());
        checkoutDay.setSelectedItem(r.getOutDay());
    }//GEN-LAST:event_editRoomButtonActionPerformed

    private void deleteRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoomButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jListRoom.getSelectedIndex();
        if (selectedIndex == -1) {
            roomListModel.removeAllElements();
        } else {
            roomListModel.remove(selectedIndex);
        }
    }//GEN-LAST:event_deleteRoomButtonActionPerformed

    private void addRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomButtonActionPerformed
        String typeString = selectRoomType.getSelectedItem().toString();
        String numberString = selectNumber.getSelectedItem().toString();
        String inMonthString = checkinMonth.getSelectedItem().toString();
        String inDayString = checkinDay.getSelectedItem().toString();
        String outMonthString = checkoutMonth.getSelectedItem().toString();
        String outDayString = checkoutDay.getSelectedItem().toString();
        
        Room r = new Room(typeString, numberString, inMonthString, inDayString, outMonthString, outDayString);
        
        if (r.isNotEmpty()) {
            if (r.rightDate()) {
                roomEmpty();
                roomListModel.addElement(r);
                jListRoom.setModel(roomListModel);
            } else {
                JOptionPane.showMessageDialog(null, "Please correct the check-in and check-out date.", "Date Error", JOptionPane.ERROR_MESSAGE);
            }           
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in the blank.", "Room Information Missing", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_addRoomButtonActionPerformed

    public void roomEmpty() {
        selectRoomType.setSelectedIndex(0);
        selectNumber.setSelectedIndex(0);
        checkinMonth.setSelectedIndex(0);
        checkinDay.setSelectedIndex(0);
        checkoutMonth.setSelectedIndex(0);
        checkoutDay.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }
    DefaultListModel customerListModel = new DefaultListModel();
    DefaultListModel roomListModel = new DefaultListModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addRoomButton;
    private javax.swing.JPanel backGround;
    private javax.swing.JLabel checkin;
    private javax.swing.JComboBox<String> checkinDay;
    private javax.swing.JComboBox<String> checkinMonth;
    private javax.swing.JLabel checkout;
    private javax.swing.JComboBox<String> checkoutDay;
    private javax.swing.JComboBox<String> checkoutMonth;
    private javax.swing.JButton deleteCustomerButton;
    private javax.swing.JButton deleteRoomButton;
    private javax.swing.JButton editCustomerButton;
    private javax.swing.JButton editRoomButton;
    private javax.swing.JLabel familyName;
    private javax.swing.JTextField familyNameField;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel idNumber;
    private javax.swing.JTextField idNumberField;
    private javax.swing.JLabel jLabelMap;
    private javax.swing.JList<String> jListCustomer;
    private javax.swing.JList<String> jListRoom;
    private javax.swing.JPanel jPanelInfoCustomer;
    private javax.swing.JPanel jPanelInfoRoom;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel number;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel roomType;
    private javax.swing.JComboBox<String> selectNumber;
    private javax.swing.JComboBox<String> selectRoomType;
    // End of variables declaration//GEN-END:variables
}
